### ISSUE TITLE
Sankey dataflow diagram unreadable in dark theme

### ISSUE THREAD

**Issue by stefanb** [SterArcher/OHCA-registry-Slovenia#1]
Example with GitHub set to dark theme:
<img width="147" alt="image" src="https://user-images.githubusercontent.com/319826/159158731-4c1c0004-657f-4e16-afad-4fb69fcaba25.png">

I suggest to render image of the diagram without transparent background, to have the expected result.

**Comment by evgenijja** [comment]
Thank you for catching this! I think I managed to fix it now.

**Comment by stefanb** [comment]
Tnx, it's ok now!
