### ISSUE TITLE
Compliance EMS software form

### ISSUE THREAD

**Issue by rokmik** [SterArcher/OHCA-registry-Slovenia#10]
- [x] "Ni zabeleženo/ni znano" je en in isti odgovor.
<img width="181" alt="Screenshot 2022-07-02 at 23 25 34" src="https://user-images.githubusercontent.com/100420171/177016564-2246627e-6017-46e5-9ae3-c779d93ad8be.png">
<img width="401" alt="Screenshot 2022-07-02 at 23 25 42" src="https://user-images.githubusercontent.com/100420171/177016570-bc3922f6-4566-4a26-8618-303ce4c3007c.png">

- [x] Vzrok srčnega zastoja ni video recordingu iz Adobe XD. Preveri rposim sam, če se ujema. 
<img width="542" alt="Screenshot 2022-07-02 at 23 38 17" src="https://user-images.githubusercontent.com/100420171/177016822-32df788c-e13f-4dc0-87ae-2f8f649d866a.png">

- [x] Manjka odgovor "99 neznano"
<img width="788" alt="Screenshot 2022-07-02 at 23 39 03" src="https://user-images.githubusercontent.com/100420171/177016838-a678882d-2a2f-4e5f-9c67-0ae3a753f31f.png">

- [x] Manjka "Država zastoja"
<img width="608" alt="Screenshot 2022-07-02 at 23 53 03" src="https://user-images.githubusercontent.com/100420171/177017115-02def1cc-ce45-4241-b8ab-cfb971fe362f.png">

- [x] Manjka "Število prebivalcev, ki jih pokriva vaš NMP"
<img width="546" alt="Screenshot 2022-07-02 at 23 53 40" src="https://user-images.githubusercontent.com/100420171/177017125-141eda58-fe7f-41ad-8e63-d0e0a22b8540.png">

- [x] Manjka "ID pacienta"
<img width="549" alt="Screenshot 2022-07-02 at 23 54 12" src="https://user-images.githubusercontent.com/100420171/177017137-384df13b-ec5f-4d6f-91e2-cf37bb5566a4.png">

- [x] Manjka "Bolnik umrl na terenu?"
<img width="381" alt="Screenshot 2022-07-02 at 23 56 26" src="https://user-images.githubusercontent.com/100420171/177017183-6602d483-bbcb-4667-a6d6-411e4761ecb1.png">

- [x] Manjka "Mesec odpusta iz bolnišnice?"
<img width="228" alt="Screenshot 2022-07-02 at 23 56 53" src="https://user-images.githubusercontent.com/100420171/177017199-636c4db9-fd83-4a43-bbd3-813024a067f6.png">

- [x] Manjka "Dan odpusta iz bolnišnice?"
<img width="241" alt="Screenshot 2022-07-02 at 23 57 18" src="https://user-images.githubusercontent.com/100420171/177017206-6a4cc6c5-7242-4bda-a122-501e4347a43a.png">

- [x] Manjka "Preživetje do odpusta iz bolnišnice"
<img width="545" alt="Screenshot 2022-07-02 at 23 57 45" src="https://user-images.githubusercontent.com/100420171/177017214-5d424ef5-6302-4548-891f-728524a60e78.png">

- [x] Manjka "30-dnevno preživetje po zastoju?"
<img width="497" alt="Screenshot 2022-07-02 at 23 58 16" src="https://user-images.githubusercontent.com/100420171/177017222-b96d6bcc-1966-4685-930f-c9f996a7a4c5.png">

**Comment by SterArcher** [comment]
ad manjka država --> to je samoumevno, da je Slovenija ignore that.
število prebivalcev se generira avtomatsko.  
id pacienta se generira avtomatsko --> ime + priimek+  datum rojstva +  datum dogodka
mesec odpusta/dan odpusta/ 30d preživetje --> to ne morejo na terenu vpisat to je tudi ok, da ni noter

ostalo je pa treba uredit.

Hvala @rokmik za seznam popravkov.
