### ISSUE TITLE
Design enhancement, TTM vzporedno ºC

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#17]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/29688990/180073551-bf84b407-085d-4b11-b55c-e87c2cd87fd5.png">
Tole bi blo ekstra kul, če bi bilo v taki obliki

<img width="89" alt="image" src="https://user-images.githubusercontent.com/29688990/180073688-f6e31428-b9ca-4b0c-9929-cbac67630f4f.png">

**Comment by gasperTheGhost** [comment]
Resolved with commit [ef525ba](https://github.com/SterArcher/OHCA-registry-Slovenia/commit/ef525baa505ace6452f5119ffa9e8c55148c08e7)
