### ISSUE TITLE
Enhancement subscript pri CO2 in O2

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#18]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/29688990/180075342-47e5d918-c908-4851-9690-796f38605ac6.png">

 CO₂ in O₂

**Comment by gasperTheGhost** [comment]
Resolved with commit [b321bf3](https://github.com/SterArcher/OHCA-registry-Slovenia/commit/b321bf314fd8a8f5f325cb6ff1e22f79cfa61daf)
