### ISSUE TITLE
UI intervention ID

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#23]
Torej takole bi bilo super, da bi imeli za vpis intervencije.

> pozor gif je, samo traja, da se naloži

![Screen Recording 2022-07-21 at 22 53 58](https://user-images.githubusercontent.com/29688990/180314355-f190d3c7-b3f0-40b9-b683-b0834e2a2b33.gif)

Pa še en vir tukaj: https://codepen.io/bradeneast/pen/YzzMoGw 

Hkrati mora biti vse skupaj narejeno na način da pove spodaj oz. izpiše iz številke zgoraj.

- [x] DSZ center (lj/mb)
- [x] datum --> to bi potem lahko se samoizpolnilo tudi spodaj, kjer je datum treba
- [x] pa zaporedna številka intervencije za tisti dan

**Comment by gasperTheGhost** [comment]
Prvotna implementacija končana as of [commit acf0f0](https://github.com/SterArcher/OHCA-registry-Slovenia/commit/acf0f012ee4a6667f5418d03ba952e576cb64067).

Za zaprtje problema predlagam še:
- [ ] Sprememba barve sija za očitno napačna polja

**Comment by SterArcher** [comment]
Oh wow, nice! @gasperTheGhost, mi je zelo všeč!  ##


jaz bi dodal tudi sij barve polja, ko je enkrat izpolnjeno?

predlagam

- [ ] zelena za pravilno
- [ ] rdeča za napačno

dodatno je treba popravit

- [ ] številka intervencije --> dnevna številka intervencije (ker se spremeni vsak dan)

In dodat

- [ ] datum intervencije (trenutno imamo samo DSZ center in št intervencije

<img width="617" alt="image" src="https://user-images.githubusercontent.com/29688990/180385387-63f3aa6c-41e0-4e84-a8dd-242bac9a3bcc.png">

**Comment by SterArcher** [comment]
Nicely done!
