### ISSUE TITLE
feature update: underline form titles

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#25]
Naslovi formov so zdaj dosti crowded in obsežni. Da se lahko loči vizualno kaj je kaj, dodajmo animirano linijo, ko hooveraš over the title in underline, ko izbereš form, da veš na katerem si. Trenutno je lepo narejeno, da je sivo kar ni izbrano pa belo kar je, samo bi to morda še lepše naredilo vse skupaj. 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/29688990/181354225-06b16413-3a3a-4a33-9141-ea26a20ce3b1.png">

https://css-irl.info/animating-underlines/
Od tukaj bi vzel underline 3 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/29688990/181354158-014dbdd0-a936-4a72-bfbf-28525541815a.png">

**Comment by gasperTheGhost** [comment]
Resolved with commit [f3d5fe4](https://github.com/SterArcher/OHCA-registry-Slovenia/commit/f3d5fe4fae3c6d36ffb38ffffb3b35ea4548fb79)
