### ISSUE TITLE
Online form corrections - dan dogodka

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#4]
Zdravo,

torej treba je popraviti naslednje zadeve.

- [x] Strani naj bo ime SiOHCA vpisovanje podatkov + naj ima logo našega projekta, tako kot spletna stran (https://github.com/SterArcher/OHCA-registry-Slovenia/blob/gh-pages/assets/img/favicon.png) 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/29688990/173196849-3fb7ef74-fe01-452c-b809-654bdcc7bbf3.png">

- [x] Klik na logo naj vodi na našo spletno stran siohca.um.si
<img width="161" alt="image" src="https://user-images.githubusercontent.com/29688990/173196891-0939bdfd-a788-4601-93f2-8e9b60e1a86b.png">

- [x] Datumi
tukaj so datumi v angleščini, to je treba prevesti v slo.
Dodatno je treba tudi spremeniti zaporedje v DAN-MESEC-LETO
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/29688990/172776347-be11621b-1aaf-4c48-b91f-890d4821f61f.png">

- [x] UIID sistema

naj si sledijo po abecedi
treba je ozg gorenjske nadomestiti, poglej mail in [trello](https://trello.com/c/qS94eZRJ/181-korekcija-seznama-nmp)
<img width="866" alt="image" src="https://user-images.githubusercontent.com/29688990/172776428-21e66197-cb00-4344-8a94-1f11f56e0318.png">

- [x] UIID območja
Naj se uredi po abecedi

<img width="866" alt="image" src="https://user-images.githubusercontent.com/29688990/172776638-832069e2-2731-42cd-8d43-071c25ee39b1.png">

- [x] Datum rojstva
tukaj ne more biti oboje notr napisano.
Ali se napiše datum rojstva oz. se napiše starost
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/29688990/172776744-85dd160c-b941-4d0c-9b35-8634aff77859.png">

- [x] priča zastoja
Prosim preveri ali mankajo tudi prvi posredovalci?
<img width="210" alt="image" src="https://user-images.githubusercontent.com/29688990/172776878-90d7db41-2c60-4f72-a419-bd932176405e.png">

- [x] Odziv očividca
Tukaj je morda lahko tudi samo tpo ventiliranje? Preveri tabelo
<img width="378" alt="image" src="https://user-images.githubusercontent.com/29688990/172776984-97239666-f113-47ce-93a0-5aa402018f7f.png">

- [x] Začetek izvajanja TPO
Tukaj je treba dati time stamp
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/29688990/172777010-9fd4355d-ed9b-42d9-bdd7-6748e5f2705b.png">

- [x] čas prvega aed šoka očividcov
Tukaj je treba dati time stamp

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/29688990/172777099-88ff7c98-3144-4070-ad67-fa9f921042c0.png">

- [x] odzivni čas
tole bi morali izračunati mi in ne rabi biti za izpolnit
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/29688990/172777261-b1e1ae3b-4315-4a96-90c8-e67b7960ed93.png">

- [x] ciljana temperatura
tole more bit v celzija

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/29688990/172777358-080a1cd3-0e05-4349-a41f-607a745c7ad5.png">

- [ ] #27
imajo radio button, če jih hočeš zbrat več mora biti za obkljukat
<img width="631" alt="image" src="https://user-images.githubusercontent.com/29688990/172777421-79c27d0b-fa38-4d8d-9f0f-84ffa01fd301.png">

- [x] kvaliteta TPO
<img width="175" alt="image" src="https://user-images.githubusercontent.com/29688990/172777503-62dfa4fd-2e37-4de3-8a0d-e1a7312450a6.png">

Tole bo treba bolje definirat

- [x] čas rosc
tukaj raje napiši time stamp pa bomo potem mi računali koliko časa je minilo
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/29688990/172777665-5ea473df-5e53-4906-a843-6a51c3de3b5e.png">

- [x] država zastoja
to vemo, da je slovenija 🇸🇮
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/29688990/172777700-627f4047-2629-4148-8c96-785a48b7da2c.png">

- [x] Regija srčnega zastoja, to bi jaz želel iz kontroliranega seznama
https://www.stat.si/obcine/sl

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/29688990/172777745-37f6a689-92ed-40b5-9ac8-bf01fb30d0b5.png">

- [x] starost očividca
tukaj mora biti nujno za obkljukat tudi ali je starost ocenjena ali ne
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/29688990/172777957-8761b6e2-9f39-4560-bb19-89c927636cb2.png">

**Comment by SterArcher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [popravki za obrazec - ob sprejemu](https://trello.com/c/kOFTXHFz/183-popravki-za-obrazec-ob-sprejemu)

**Comment by evgenijja** [comment]
1. Glede datumov - uspele sva prevesti mesece ne pa spremenit vrstnega reda dan-mesec-leto. Sva pa nasli se en drug kul widget. Trenutno sta notri obe varianti da se lahko odlocimo
2. Da lahko popravim tisti OZG Gorenjske moram na novo nafilat bazo tko da bo se malo trajalo
3. Starost sem vrgla ven in napisala funkcijo ki jo zracuna iz datuma rojstva - starost na dan dogodka (ne glede na blizino rojstngea dne) 
4. Pri timestampih sta dve moznosti - prva da se vpise cas v formatu hh:mm:ss na roke, druga da se uporabi nek widget (glej /formpage 'čas prvega AED' ampak pri widgetu zdruzljivem z crispy forms nisem uspela nastimat sekund, widget kjer pa so sekunde pa ne znam nardit crispy hah

**Comment by SterArcher** [comment]
1. datumi všeč mi je novi widget in ga prosim uporabite tudi drugje. Torej tale, ko se mu mali koledarček odpre.
![image](https://user-images.githubusercontent.com/29688990/176180672-48a2fc5d-5177-4f91-8b2b-80f3c3aeebfd.png)

3. super, hvala!

4. mislim, da je za sekunde vseeno, bo to povedal profesor. Mi je pa ušeč kako je narejeno, vseeno pa bi moral biti zraven še datum, za tiste primere, ko je intervencija trajala okoli polnoči, da ne mede sistema, ko bomo računali čase ven. Ta datum naj se samo-populira s tistim iz datum srčnega zastoja, da prihranijo na času. Če bo napačen, bodo pa popravili.

**Comment by SterArcher** [comment]
done
