### ISSUE TITLE
bug: cookie restart

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#46]
Ko je obrazec oddan se mora vse notri izbrisati. Zdaj ostane po izpolnjenem obrazcu vse shranjeno in moraš da vpišeš novega kliknit počisti vse. bolje bi bilo, da ko izpolneš in oddaš se pobriše.

**Comment by gasperTheGhost** [comment]
Fixed with commit [741ce9d](https://github.com/SterArcher/OHCA-registry-Slovenia/commit/741ce9d3309b5e0e63767c74a9a8897716a6b1e3).
