### ISSUE TITLE
bug: čas zaključka oživljanja mora biti neobvezen

### ISSUE THREAD

**Issue by SterArcher** [SterArcher/OHCA-registry-Slovenia#47]
Čas zaključka oživljanja naj bo neobvezen. Pri primeru 9 ga je treba odstraniti in dati ni podatka.

**Comment by evgenijja** [comment]
Sem popravila. Sicer pa je bilo polje obvezno samo, če je bolnik umrl na terenu. Zdaj ni v ozadju nobenega pogoja za ta timestamp.
